name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 26.0.1 # 26.1 is missing simulators on GHA as of November 2025
    - uses: actions/checkout@v4
    - name: Build & Test
      run: set -o pipefail && xcodebuild test -scheme 'GeoMonitor' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 17' | xcbeautify
