name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
jobs:
  macos:
    runs-on: macos-12 # macos-latest is still 10.15, which we don't support
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v2
    - name: Build & Test
      run: xcodebuild -scheme 'GeoMonitor' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
