name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
   
jobs:
  macos:
    runs-on: macos-12 # macos-latest is still 10.15, which we don't support
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - name: Build & Test
      run: xcodebuild test -scheme 'GeoMonitor' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' -resultBundlePath TestResults
    - uses: kishikawakatsumi/xcresulttool@v1.7.0
      with:
        path: TestResults.xcresult
      if: success() || failure()
      # ^ This is important because the action will be run
      # even if the test fails in the previous step.